//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABIEntity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BallinaDBEntities : DbContext
    {
        public BallinaDBEntities()
            : base("name=BallinaDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<OPC_Tags> OPC_Tags { get; set; }
    
        public virtual int spGetOPCTags()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spGetOPCTags");
        }
    
        public virtual ObjectResult<OPC_Tags> spGetOPCTags1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<OPC_Tags>("spGetOPCTags1");
        }
    
        public virtual ObjectResult<OPC_Tags> spGetOPCTags1(MergeOption mergeOption)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<OPC_Tags>("spGetOPCTags1", mergeOption);
        }
    }
}
