//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABIEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPC_Tags
    {
        public int UID { get; set; }
        public string Node { get; set; }
        public string DeviceGroupName { get; set; }
        public string TagName { get; set; }
        public string TagType { get; set; }
        public Nullable<byte> IsTag { get; set; }
        public Nullable<int> RID { get; set; }
    }
}
